// Do not edit this file! It was automatically generated.

#ifndef GEN_TYPES_SAV_H
#define GEN_TYPES_SAV_H

#include "buildin:bindless.h"

// Text_UBO
RegisterUniform(TextUBO, {
	uint glyph;
	vec3 color;
});

#define getTextUBO(handle) GetResource(TextUBO, handle)


// Base_UBO
RegisterUniform(BaseUBO, {
	vec3 color;
});

#define getBaseUBO(handle) GetResource(BaseUBO, handle)


// Camera_UBO
RegisterUniform(CameraUBO, {
	mat4 view;
	mat4 projection;
	vec3 position;
});

#define getCameraUBO(handle) GetResource(CameraUBO, handle)


#endif